#!/usr/bin/env python3
"""PSAM Scaling QLD — the desktop launcher.

The project holds several tools rather than one program, so the .app in macos/
opens this menu and each tool is launched from it. Generated by
../mac_app_tools/gen_launcher.py; the TOOLS table below is the only part that
differs between the NSW, VIC and QLD copies.

Two launch kinds, and the choice matters:

  gui       Started detached, with no console. Right for the tkinter editors —
            the window is the whole interface, and the launcher must not sit in
            front of them or die with them.
  terminal  Started in a Terminal window via a generated .command. Right for
            anything that prints its results or calls input(), and for the
            Streamlit server, which needs a visible log and a working Ctrl+C.
            Launching those detached would swallow the output, or leave an
            invisible process holding a port.

Each tool runs under its own folder's .venv when it has one and the project
root's .venv otherwise, so the existing per-folder environments keep working
untouched.
"""

import os
import shlex
import subprocess
import sys
import tempfile
import tkinter as tk
from pathlib import Path
from tkinter import messagebox, ttk

APP_NAME = "PSAM Scaling QLD"
SUBTITLE = "QCE annual scaling — QTAC"
ACCENT = "#A64FC4"

HERE = Path(__file__).resolve().parent

# (title, blurb, folder, script, kind)
TOOLS = [
    ('QCE Course Scaling',
     'Extract Tables 6-9 from the QTAC ATAR report, fit the polynomial curves, review them, and export the 25-column table.',
     'course scaling', 'qld_course_scales_app.py', 'gui'),
    ('ATAR Lookup Builder',
     'Build the aggregate-to-ATAR lookup from the scale history and write the comparison plot.',
     'atar scaling', 'build_lookup_final.py', 'terminal'),
    ('Course Scales Builder',
     'Rebuild course_scales_2025.csv from the extracted Table 6-9 data.',
     'atar scaling', 'build_course_scales_2025.py', 'terminal'),
]

NAVY = "#1E2D44"
INK = "#1E2D44"
MUTED = "#5A6B82"
PAPER = "#FFFFFF"
RULE = "#DFE5EC"


def _claim_bundle_identity():
    """Take the Dock tile and menu title off the interpreter's bundle.

    The .app is a shell script that execs python, so macOS sees the interpreter
    and would otherwise label the tile "Python". Overwriting the main bundle's
    info dictionary before the first Tk call fixes both the label and the icon.
    Cosmetic only — never block startup over it.
    """
    if sys.platform != "darwin":
        return
    try:
        from Foundation import NSBundle
        bundle = NSBundle.mainBundle()
        info = bundle.localizedInfoDictionary() or bundle.infoDictionary()
        info["CFBundleName"] = APP_NAME
        info["CFBundleDisplayName"] = APP_NAME
    except Exception:
        pass


def interpreter(folder):
    """The python for a tool: its own folder's venv, else the project root's,
    else whatever is running this launcher."""
    for venv in (HERE / folder / ".venv", HERE / ".venv"):
        py = venv / "bin" / "python"
        if py.is_file():
            return py
    return Path(sys.executable)


def launch_gui(script, py):
    # start_new_session so the tool outlives this launcher: quitting the menu
    # must not take the editor the operator is working in down with it.
    subprocess.Popen([str(py), str(script)], cwd=str(script.parent),
                     start_new_session=True)


def launch_terminal(script, py, slug):
    command = Path(tempfile.gettempdir()) / f"psam-scaling-{slug}.command"
    command.write_text(
        "#!/bin/bash\n"
        "# Generated by the PSAM Scaling launcher. Safe to delete.\n"
        # Terminal is its own process, so it does not inherit the launcher's
        # native re-exec. A translated python dies at `import numpy`.
        'if [ "$(/usr/sbin/sysctl -n sysctl.proc_translated 2>/dev/null)" = "1" ]; then\n'
        '    exec /usr/bin/arch -arm64 "$0" "$@"\n'
        "fi\n"
        f"cd {shlex.quote(str(script.parent))} || exit 1\n"
        f"{shlex.quote(str(py))} {shlex.quote(str(script))}\n"
        'echo\necho "— finished. You can close this window."\n',
        encoding="utf-8")
    command.chmod(0o755)
    subprocess.run(["/usr/bin/open", "-a", "Terminal", str(command)], check=True)


class Launcher:
    def __init__(self, root):
        self.root = root
        root.title(APP_NAME)
        root.configure(bg=PAPER)
        root.minsize(660, 380)

        style = ttk.Style()
        style.theme_use("clam")
        style.configure("Open.TButton", font=("Helvetica", 12), padding=(14, 5))

        header = tk.Frame(root, bg=NAVY)
        header.pack(fill="x")
        tk.Frame(header, bg=ACCENT, width=8).pack(side="left", fill="y")
        block = tk.Frame(header, bg=NAVY)
        block.pack(side="left", fill="x", padx=(18, 0), pady=16)
        tk.Label(block, text=APP_NAME, bg=NAVY, fg="#FFFFFF",
                 font=("Helvetica", 20, "bold")).pack(anchor="w")
        tk.Label(block, text=SUBTITLE, bg=NAVY, fg="#A8B6C8",
                 font=("Helvetica", 12)).pack(anchor="w", pady=(2, 0))

        body = tk.Frame(root, bg=PAPER)
        body.pack(fill="both", expand=True, padx=22, pady=(16, 8))
        for i, tool in enumerate(TOOLS):
            self.add_row(body, tool, last=(i == len(TOOLS) - 1))

        foot = tk.Frame(root, bg=PAPER)
        foot.pack(fill="x", padx=22, pady=(0, 14))
        self.status = tk.Label(foot, text="", bg=PAPER, fg=MUTED, anchor="w",
                               font=("Helvetica", 11))
        self.status.pack(side="left", fill="x", expand=True)
        ttk.Button(foot, text="Project folder",
                   command=self.reveal).pack(side="right")

    def add_row(self, parent, tool, last):
        title, blurb, folder, script_name, kind = tool
        script = HERE / folder / script_name
        row = tk.Frame(parent, bg=PAPER)
        row.pack(fill="x", pady=(0, 12 if not last else 0))

        text = tk.Frame(row, bg=PAPER)
        text.pack(side="left", fill="x", expand=True)
        tk.Label(text, text=title, bg=PAPER, fg=INK, anchor="w",
                 font=("Helvetica", 14, "bold")).pack(anchor="w", fill="x")
        note = blurb if script.is_file() else f"Missing: {folder}/{script_name}"
        tk.Label(text, text=note, bg=PAPER, fg=MUTED, anchor="w", justify="left",
                 wraplength=430, font=("Helvetica", 11)).pack(anchor="w", fill="x")

        button = ttk.Button(row, text="Open", style="Open.TButton",
                            command=lambda: self.open(tool, script))
        button.pack(side="right", padx=(16, 0))
        if not script.is_file():
            button.state(["disabled"])

        if not last:
            tk.Frame(parent, bg=RULE, height=1).pack(fill="x", pady=(0, 12))

    def open(self, tool, script):
        title, _, folder, script_name, kind = tool
        py = interpreter(folder)
        try:
            if kind == "gui":
                launch_gui(script, py)
                self.say(f"Opened {title}. Its window may take a moment.")
            else:
                slug = script_name.rsplit(".", 1)[0].replace("_", "-")
                launch_terminal(script, py, slug)
                self.say(f"Opened {title} in Terminal.")
        except Exception as exc:
            messagebox.showerror(
                APP_NAME,
                f"Could not start {title}.\n\n{exc}\n\n"
                f"Interpreter: {py}\nScript: {script}")

    def reveal(self):
        subprocess.run(["/usr/bin/open", str(HERE)], check=False)

    def say(self, message):
        self.status.config(text=message)
        self.root.after(9000, lambda: self.status.config(text=""))


def main():
    _claim_bundle_identity()
    os.chdir(HERE)
    root = tk.Tk()
    Launcher(root)
    root.mainloop()


if __name__ == "__main__":
    main()
